In [2]:
import numpy as np
import cv2
import tifffile as tiff
from PIL import Image

In [24]:
original = tiff.imread("new_data/original.tif")
hori = tiff.imread("new_data/horiz_data.tif")
output = tiff.imread("CV_Output/cv_navier_stokes/tif output/cv_hoiz_nv.tif")
deep = tiff.imread("Deep_Prior/Horizontal_Deep_prior_tif.tif")

In [25]:
original

array([[1265, 1245, 1274, ..., 1286, 1291, 1220],
       [1297, 1282, 1272, ..., 1265, 1293, 1240],
       [1306, 1302, 1327, ..., 1254, 1311, 1269],
       ...,
       [1181, 1146, 1169, ..., 1274, 1277, 1240],
       [1251, 1189, 1203, ..., 1314, 1271, 1228],
       [1303, 1205, 1198, ..., 1223, 1209, 1171]], dtype=uint16)

In [26]:
hori

array([[1265, 1245, 1274, ..., 1286, 1291, 1220],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       ...,
       [1181, 1146, 1169, ..., 1274, 1277, 1240],
       [1251, 1189, 1203, ..., 1314, 1271, 1228],
       [1303, 1205, 1198, ..., 1223, 1209, 1171]], dtype=uint16)

In [27]:
output

array([[1265, 1245, 1274, ..., 1286, 1291, 1220],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       ...,
       [1181, 1146, 1169, ..., 1274, 1277, 1240],
       [1251, 1189, 1203, ..., 1314, 1271, 1228],
       [1303, 1205, 1198, ..., 1223, 1209, 1171]], dtype=uint16)

In [28]:
# float 32 to uint 16
deep

array([[[0.8405866 , 0.8383548 , 0.8371399 , ..., 0.7970166 ,
         0.7965185 , 0.79062253],
        [0.8460218 , 0.8445478 , 0.84368426, ..., 0.78797567,
         0.78668034, 0.7833914 ],
        [0.84095293, 0.8366065 , 0.83612406, ..., 0.77818006,
         0.7772825 , 0.781669  ],
        ...,
        [0.40522403, 0.367409  , 0.34150875, ..., 0.729599  ,
         0.7180975 , 0.7162656 ],
        [0.6063534 , 0.5871776 , 0.57108676, ..., 0.72903836,
         0.7182707 , 0.72103167],
        [0.73776037, 0.71947706, 0.7187649 , ..., 0.7271338 ,
         0.7169424 , 0.7224633 ]]], dtype=float32)